version: "2.3"

services:
  autogoal:
    container_name: autogoal
    hostname: autogoal
    image: autogoal/autogoal
    ports:
      - 8501:8501
      - 8000:8000
    volumes: 
      - "./autogoal:/usr/lib/python3/dist-packages/autogoal"
      - ".:/home/coder/autogoal"
      - "~/.ssh:/home/coder/.ssh"
    user: "1000:1000"
